name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: |
          flake8 src tests
          black --check src tests
      - name: Run tests
        run: pytest -q
      - name: Train (smoke)
        run: python -m src.train
      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-v0.1
          path: models/


